name: Rust CI & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview, clippy

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Cargo Check
        run: cargo check --locked

      - name: Run Cargo Clippy
        run: cargo clippy --locked --all-targets -- -D warnings

      - name: Run Unit & Integration Tests (via llvm-cov)
        run: cargo llvm-cov --all-targets --workspace --lcov --output-path lcov.info

      - name: Run Custom Integration Tests Script
        run: ./tests/integration_tests.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
